### ISSUE TITLE
private method prepend called

### ISSUE THREAD

**Issue by jbodah** [backupify/minitest-tagz#13]
Failing for ruby 2.0.0

```
/home/travis/build/jbodah/spotifuby/vendor/bundle/ruby/2.0.0/gems/minitest-tagz-1.2.1/lib/minitest/tagz.rb:53:in `patch': private method `prepend' called for #<Class:Minitest> (NoMethodError)

    from /home/travis/build/jbodah/spotifuby/vendor/bundle/ruby/2.0.0/gems/minitest-tagz-1.2.1/lib/minitest/tagz.rb:63:in `<module:Tagz>'

    from /home/travis/build/jbodah/spotifuby/vendor/bundle/ruby/2.0.0/gems/minitest-tagz-1.2.1/lib/minitest/tagz.rb:5:in `<module:Minitest>'

    from /home/travis/build/jbodah/spotifuby/vendor/bundle/ruby/2.0.0/gems/minitest-tagz-1.2.1/lib/minitest/tagz.rb:4:in `<top (required)>'

    from /home/travis/build/jbodah/spotifuby/spec/spec_helper.rb:15:in `require'

    from /home/travis/build/jbodah/spotifuby/spec/spec_helper.rb:15:in `<top (required)>'

    from /home/travis/build/jbodah/spotifuby/spec/bot_spec.rb:1:in `require'

    from /home/travis/build/jbodah/spotifuby/spec/bot_spec.rb:1:in `<top (required)>'

    from /home/travis/build/jbodah/spotifuby/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:15:in `require'

    from /home/travis/build/jbodah/spotifuby/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:15:in `block in <main>'

    from /home/travis/build/jbodah/spotifuby/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `select'

    from /home/travis/build/jbodah/spotifuby/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `<main>'

rake aborted!

Command failed with status (1): [ruby -I"lib:spec" -I"/home/travis/build/jbodah/spotifuby/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib" "/home/travis/build/jbodah/spotifuby/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "spec/bot_spec.rb" "spec/spotify/async/song_event_listener_spec.rb" "spec/spotify/player_spec.rb" "spec/spotify_spec.rb" ]
```

**Comment by jbodah** [comment]
Fixed in 1.2.2
